version: '3'
services:
  express-app:
    build:
      context: .
    ports:
      - "3306:3306"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Quocdung0203
      MYSQL_DATABASE: resdb
